project_id: 2
api_token: 79c2e6c51241fae421d5a41eac589a174ca7692e1049fe763b42ceda4433fd0f1cbbf7f49f01d4b0
files:
  - source: /GeoBus/en.xcloc/Source\ Contents/GeoBus/en.lproj/*.strings
    translation: /GeoBus/%osx_code%/%original_file_name%
